version: '2'
services:

  scheduler-api:
    container_name: scheduler-api
    image: scheduler/api
    environment:
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
      - 'ASPNETCORE_URLS=http://+:80'
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=Docker
      - DOTNET_VERSION=3.0.0
      - ASPNETCORE_VERSION=3.0.0
    ports:
      - '57120:80'
      - '44326:443'
    networks:
      scheduler-network:
        ipv4_address: 172.16.1.101
    depends_on:
      - scheduler-es
      - scheduler-db
      - scheduler-bus

  scheduler-es:
    container_name: scheduler-es
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: SessionLoggerEventStore
    ports:
      - '27017:27017'
    networks:
      scheduler-network:
        ipv4_address: 172.16.1.102

  scheduler-db:
    container_name: scheduler-db
    image: postgres:12.0-alpine
    environment:
      POSTGRES_DB: 'SchedulerReadModel'
      POSTGRES_USER: 'scheduler_user'
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'
    expose:
      - '5432'
    networks:
      scheduler-network:
        ipv4_address: 172.16.1.103

  scheduler-bus:
    container_name: scheduler-bus
    image: 'rabbitmq:3-management'
    ports:
      - '15672:15672'
      - '5672:5672'
    networks:
      scheduler-network:
        ipv4_address: 172.16.1.104

networks:
  scheduler-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
          gateway: 172.16.1.1